# Generated by Django 4.2.7 on 2024-02-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='get_default_profile_image', max_length=255, null=True, upload_to='get_profile_image_filepath'),
        ),
    ]
