# Generated by Django 4.2.8 on 2024-03-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_cart_user_alter_order_user'),
        ('accounts', '0003_account_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
